<% if task.errors.any? %>
  <div class="alert alert-danger" role="alert">
    <h2><%= pluralize(task.errors.count, "個のエラーがあるため、保存できません。") %></h2>
    <ul>
      <% task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_with(model: task, local: true, url: change_root ) do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :detail %>
    <%= f.text_field :detail, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :priority %>
    <%= f.select :priority, Task.priorities_i18n.invert, {}, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :situation %>
    <%= f.select :situation, Task.situations_i18n.invert, {}, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :deadline %>
    <%= f.datetime_field :deadline, class: "form-control" %>
  </div>

  <% case action_name %>
  <% when "new" %>
    <%= f.submit t('helpers.submit.create') %>
  <% when "edit" %>
    <%= f.submit t('helpers.submit.update') %>  
  <% end %>
<% end %>

<%= link_to t('helpers.submit.task_index'), tasks_path %>
